services:
  web:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    image: ttv-rec-web:latest
    container_name: ttv-rec-web
    restart: unless-stopped
    networks:
      tncb:
        aliases:
          - ttv-rec

networks:
  tncb:
    external: true
    name: tncb-net
